server:
  port: 8080
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carsale?characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.gxyan.pojo
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
jwt:
    expiration: 3600
    header: Authorization